apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.database.user }}

          volumeMounts:
            - name: mysql-password
              mountPath: /run/secrets/mysql_password
              subPath: mysql_password
              readOnly: true

      volumes:
        - name: mysql-password
          secret:
            secretName: mysql-password